"""areas actividades peligros base

Revision ID: 03c577309fbd
Revises: 40b8a69b3698
Create Date: 2026-05-11 21:22:45.692823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c577309fbd'
down_revision = '40b8a69b3698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_peligro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peligros_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_peligro_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('riesgo_consecuencia', sa.Text(), nullable=False),
    sa.Column('p_sin', sa.Integer(), nullable=False),
    sa.Column('s_sin', sa.Integer(), nullable=False),
    sa.Column('nivel_sin', sa.String(length=20), nullable=False),
    sa.Column('medidas_control', sa.Text(), nullable=False),
    sa.Column('p_con', sa.Integer(), nullable=False),
    sa.Column('s_con', sa.Integer(), nullable=False),
    sa.Column('nivel_con', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('requisito_legal', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['tipo_peligro_id'], ['tipos_peligro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peligros_base')
    op.drop_table('actividades')
    op.drop_table('tipos_peligro')
    op.drop_table('areas')
    # ### end Alembic commands ###
