"""agregar tablas cargo y obra

Revision ID: 40b8a69b3698
Revises: 8ac863302ebd
Create Date: 2026-05-11 20:24:05.300275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b8a69b3698'
down_revision = '8ac863302ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('lat_centro', sa.Float(), nullable=True),
    sa.Column('lon_centro', sa.Float(), nullable=True),
    sa.Column('radio_perimetro', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('obra_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cargos', ['cargo_id'], ['id'])
        batch_op.create_foreign_key(None, 'obras', ['obra_id'], ['id'])
        batch_op.drop_column('cargo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cargo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('obra_id')
        batch_op.drop_column('cargo_id')

    op.drop_table('obras')
    op.drop_table('cargos')
    # ### end Alembic commands ###
