"""tabla peligros adicionales

Revision ID: 8e745ff519dd
Revises: e693a3db0573
Create Date: 2026-05-17 20:37:00.858110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e745ff519dd'
down_revision = 'e693a3db0573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peligros_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('riesgo_consecuencia', sa.Text(), nullable=False),
    sa.Column('p_sin', sa.Integer(), nullable=False),
    sa.Column('s_sin', sa.Integer(), nullable=False),
    sa.Column('nivel_sin', sa.String(length=20), nullable=False),
    sa.Column('medidas_control', sa.Text(), nullable=False),
    sa.Column('p_con', sa.Integer(), nullable=False),
    sa.Column('s_con', sa.Integer(), nullable=False),
    sa.Column('nivel_con', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_iperc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peligros_adicionales')
    # ### end Alembic commands ###
