"""agregar campo debe_cambiar_clave

Revision ID: f6e0f5006f54
Revises: 624267f43243
Create Date: 2026-05-24 00:30:07.821688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e0f5006f54'
down_revision = '624267f43243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('debe_cambiar_clave', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('debe_cambiar_clave')

    # ### end Alembic commands ###
